# Agradecemos por escolher o LeafPunish ♥
# Desejamos que tudo ocorra da melhor forma para você,
# e que seus esforços sejam recompensados!

# Seção de configuração do banco de dados individual
database:
  # Tipos disponíveis:
  # ==> SQLite
  # ==> MySQL
  type: SQLite

  # Caso esteja 'true', não usará o banco de dados global do LeafPlugins (NÃO ATIVE SEM TER CERTEZA)
  # Caso não saiba, você pode configurar todos os banco de dados dos plugins Leaf através do LeafPlugins
  enable: false

  # Configurações para o banco de dados MySQL
  mysql:
    host: 'localhost'
    user: 'root'
    password: ''
    port: 3306
    database: 'leaf'

  # Configurações de pool da conexão MYSQL (AVANÇADO)
  pool-settings:
    enable: true
    max-pool-size: 30
    min-idle: 10
    max-lifetime: 1800000 # 30 minutos
    connection-timeout: 5000 # 5 segundos

# Ativar/desativar modo de depuração
# Quando ativado, o plugin registrará informações detalhadas de depuração
# Útil para diagnóstico de problemas
debug-mode: false

# Ativará o filtro Log4j para desativar logs de desconnects (Necessário reiniciar)
log-filter: false

# Caso você coloque o LeafPunish nos Spigots para ter os menus, ative esta opção
# para que ele não registre comandos que conflitem e outros ajustes automáticos
# (Necessário reiniciar)
spigot-backend: false

# Lista de nicknames que não poderão ser punidos
blocked-nicks:
  - "nome-aqui"

# Comandos que não poderão ser usados quando estiver silenciado
blocked-mute-commands:
  - "/g"
  - "/l"
  - "/r"
  - "/tell"

# Hierarquia dos cargos
# Lembre-se de deixar exatamente como está em seu plugin de permissões
# Caso o cargo do jogador seja inferior ao alvo, a punição será cancelada
# Para desativar, deixe desta forma:
# group-hierarchy: []
group-hierarchy: [ "Master", "Admin", "Mod", "Helper", "default" ]

# Fará com que a hierarquia seja pelo peso do grupo ao em vez da lista
group-hierarchy-weight: true

# Fará que a prova precise começar com um destes endereços
# Caso a lista esteja vazia, não exigirá nenhum endereço específico
proof-domains:
  - "https://"
  - "youtube.com"
  - "prints.com"

# Servidores BungeeCord permitidos para serem selecionados nas punições
allowed-servers:
  - "RankUP"
  - "Lobby"
  - "Survival"
  - "HungerGames"
  - "SkyWars"

ban-redirect:
  # Fará que os jogadores que estiverem banidos de forma GLOBAL
  # sejam redirecionados para o servidor selecionado
  # ao em vez de serem desconectados ao entrar
  enable: false

  # Servidor padrão do BungeeCord (O jogador será redirecionado caso seja desbanido)
  defaultServer: "Lobby"

  # ID do servidor BungeeCord
  serverName: "bans"

  # Comandos permitidos no servidor de bans
  allowed-commands:
    - "/login"
    - "/logar"
    - "/autenticar"
    - "/site"
    - "/discord"

punishment:
  # Caso a punição seja Global, esta será a mensagem
  global: "Todos"

  # Caso a punição não haja uma prova definida esta será a mensagem
  no-proof: "Nenhuma"

  # Caso a punição não haja um motivo definido esta será a mensagem
  no-reason: "Nenhum motivo"

  # Caso a punição seja feita pelo console, este será o nome do autor
  console-name: "Servidor"

options:
  # Nome do servidor que o jogador será punido
  # Caso esteja "Global" as punições feitas neste servidor servirá para todos
  # que utilizarem o mesmo banco de dados
  server: "Global"

  # Fará que o autor possa selecionar o servidor que o jogador vai ser punido
  select-server: true

  # Usará os anúncios de punições
  broadcasts: true

  # Notificar o jogador quando entrar caso esteja punido
  # Exemplo: Silenciamentos
  notify-join: true

  # O staffer poderá punir ele mesmo. (É recomendado que apenas ative para testar o plugin)
  self-punish: true

  # Fará que seja obrigatório inserir uma prova ao punir (fora do /punir)
  # Caso esteja 'true', o motivo também será obrigatório
  requires-proof: false

  # Fará que seja obrigatório confirmar ao punir (/punir)
  requires-confirm: true

  # Fará que seja obrigatório inserir um motivo ao punir
  requires-reason: true

  # Caso a punição não haja uma evidência definida, a linha que possuir %proof% será pulada
  # Exemplo: disconnects, warns e broadcasts
  skip-proof-lines: true

  # Fará que a punição silenciosa envie o webhook para o discord normalmente
  # Para usar, é necessário que no motivo da punição termine com "-s"
  # Exemplo: /ban Hacker Uso de Hack -s
  silent-webhooks: true

  # [Premium]
  # Permitir que as punições tenham progresso (reasons.yml)
  # Tipos disponíveis:
  # ==> 0 (Desativar)
  # ==> 1 (Funcionará apenas no /punir)
  # ==> 2 (Funcionará em todas as punições [As que não são temporarias, exemplo: /tempmute])
  progressive-punishments: 1

  # Caso o jogador seja punido por IP, todas as contas
  # que possuirem o mesmo IP serão banidas individualmente (Contas alternativas)
  ban-alternate-accounts: true

# Opções do comando punir
punish:
  # Mensagem em cima da lista
  reasons-list-top: "§eTipos de infrações disponíveis"

  # Mensagem em baixo da lista
  reasons-list-footer: ""

  # Formato do motivo na lista
  reason-format: "&b* &f%reason%"

# [Premium]
warn:
  # Máximo de alertas até o jogador ser punido pelo motivo do aviso
  max-warns: 3

  # Duração para que a warn seja expirada
  # formato: <1min, 1h, 1d, 1m, 1a>
  # Deixe vazio para que seja permanente
  alert-duration: 1d

  # Tipo de punição que será aplicada após exceder o máximo de avisos
  type: "Mute"

  # Tipos disponíveis:
  # ==> Global (Punir em todos os servidores)
  # ==> Current (Punir no servidor definido em options.server)
  server: Global

  # Duração da punição que será aplicada após exceder o máximo de avisos
  # Deixe vazio para que seja permanente ou caso a punição não haja versão temporária
  punishment-duration: '5h'

# Broadcasts configuraveis no arquivo de mensagens
broadcasts:
  # Define se as punições devem ser anunciadas apenas no servidor onde foram aplicadas
  # Exemplo: um jogador foi banido no servidor "Survival", então o anúncio será feito somente lá
  # Útil para evitar anúncios globais em toda a rede
  announce-only-local: false

  status:
    enable: true

    # Tempo em minutos para que o status seja anunciado
    delay: 30

    # Os periodos apenas funcionam em MySQL
    # Irá listar as punições que estiverem neste período
    # Exemplo: 0 = %bans% e %mutes% será a quantia total de punições
    # Exemplo: 24 = %bans% e %mutes% será a quantia de punições no período de 24 horas
    # Exemplo: 168 = %bans% e %mutes% será a quantia de punições no período de 7 dias (24x7)
    period: 24

    # Enviará este anúncio para o console
    console-log: false

  staff:
    # Permissão necessária para receber estes anúncios
    permission: "leafpunish.announce.staff"

    # Anunciará caso um jogador tente entrar no servidor estando banido
    prevented: true

    # Avisará ao console caso um jogador tente entrar no servidor estando banido
    prevented-log: true

    # Mensagem que será enviada no console
    prevented-log-message: "&c(!) O jogador &f%player%[%address%] &ctentou entrar estando banido. (#%id%)"

  punishments:
    # Anunciará as punições de banimento
    bans: true

    # Anunciará as punições de expulsão
    kicks: true

    # Anunciará as punições de silenciamento
    mutes: true

    # Anunciará os alertas
    warns: true

    # Anunciará as revogações
    pardons: true

    # Permissão necessária para receber estes anúncios
    permission: ""
