# Agradecemos por escolher o LeafMedals ♥
# Desejamos que tudo ocorra da melhor forma para você,
# e que seus esforços sejam recompensados!

# Seção de configuração do banco de dados individual
database:
  # Tipos disponíveis:
  # ==> SQLite
  # ==> MySQL
  type: SQLite

  # Caso esteja 'true', não usará o banco de dados global do LeafPlugins (NÃO ATIVE SEM TER CERTEZA)
  # Caso não saiba, você pode configurar todos os banco de dados dos plugins Leaf através do LeafPlugins
  enable: false

  # Configurações para o banco de dados MySQL
  mysql:
    host: 'localhost'
    user: 'root'
    password: ''
    port: 3306
    database: 'leaf'

  # Configurações de pool da conexão MYSQL (AVANÇADO)
  pool-settings:
    enable: true
    max-pool-size: 30
    min-idle: 10
    max-lifetime: 1800000 # 30 minutos
    connection-timeout: 5000 # 5 segundos

# Ativar/desativar modo de depuração
# Quando ativado, o plugin registrará informações detalhadas de depuração
# Útil para diagnóstico de problemas
debug-mode: false

options:
  # Fará que sempre que o jogador altere sua medalha, atualize instantaneamente no banco de dados
  # Recomendado para desenvolvedores experientes
  database-update: true

  # Máximo de medalhas que o jogador poderá equipar
  max-medals: 3

  # Definir automaticamente no suffix do LeafTags
  # caso não esteja sendo usado um suffix customizado
  auto-suffix: false

  # Selecionar as medalhas através de menu
  # (Só funcionará desativado caso o máximo de medalhas seja 1)
  select-menu: true